repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0 # Must be kept in sync with black version in requirements.txt
    hooks:
      - id: black
        stages: [commit]
        files: ^(api/python|tools)/
        args: ["--config", "pyproject.toml"]
        exclude_types: ["json"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml", "--fix"]
        stages: [commit]
        files: ^(api/python|tools)/
        exclude_types: ["json"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write]
        stages: [commit]
        exclude_types: ["json"]
        additional_dependencies:
          - prettier@3.0.2
          - prettier-plugin-organize-imports@2.3.3
          - typescript@4.9.5
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [types-PyYAML]
        files: ^(api/python|tools/ontology-builder/src)/
