name: Convential Commit
# Validates PR title follows conventional commits

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened

jobs:
  lint-PR-title:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v3
      - uses: chanzuckerberg/github-actions/.github/actions/conventional-commits@conventional-commits-v1.4.0
