name: Updates to Ontology Files

on:
  push:
    paths:
      - "**/artifact-schemas/ontology_info_schema.json"
      - "**/artifact-schemas/all_ontology_schema.json"
      - "**/ontology-assets/ontology_info.json"
      - "**/tools/ontology-builder/src/all_ontology_generator.py"
    branches-ignore:
      - main

jobs:
  ontology-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Python cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install requirements
        run: |
          cd tools/ontology-builder
          pip install -r requirements.txt
      - name: Modified ontology info
        uses: tj-actions/changed-files@v44
        id: modified-ontology-info
        with:
          files: |
            - **ontology-info.json
      - name: setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: ontology-processing
        run: |
          python3 ./tools/ontology-builder/src/all_ontology_generator.py
          git add ./ontology-assets/*.json.gz
          git add ./ontology-assets/ontology_info.json
      - name: update API
        if: steps.modified-ontology-info.outputs.any_changed == true
        run: |
          cat ${{ github.ref }} >> ./api/python/ontology-assets-version.txt
          git add ./api/python/ontology-assets-version.txt
      - name: Commit
        run: |
          git commit -m "AUTO: update ontologies"
          git push

  update-api:
    runs-on: ubuntu-latest
    needs: ontology-processing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: check if ontology-info.json was updated
        id: check
        run: |
          echo "Checking for changes in ontology-info.json"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "ontology-assets/ontology_info.json"
          echo "::set-output name=changed::${?}"
