name: Updates Curated Lists

on:
  push:
    paths:
      - "**/tools/ontology-builder/src/curated_lists.py"
    branches-ignore:
      - main

jobs:
  ontology-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install requirements
        run: |
          pip install -r tools/ontology-builder/requirements.txt
      - name: setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: ontology-processing
        run: |
          python3 ./tools/ontology-builder/src/curated_lists.py
          git add ./tools/ontology-builder/src/ontology-references/tissue_general_list.json
          git add ./tools/ontology-builder/src/ontology-references/organ_list.json
          git add ./tools/ontology-builder/src/ontology-references/cell_class_list.json
          git add ./tools/ontology-builder/src/ontology-references/cell_subclass_list.json
          git add ./tools/ontology-builder/src/ontology-references/system_list.json
      - name: Commit
        run: |
          git commit -m "AUTO: update curated_lists"
          git push
