name: Push Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v5
      - name: lint checks
        uses: pre-commit/action@v3.0.0
