name: Tag 'Latest' Ontology Assets

on:
  push:
    paths:
      - "**/ontology-assets/**descendants.json"
      - "**/ontology-assets/**list.json"
      - "**/ontology-assets/ontology_info.json"
    branches:
      - main

jobs:
  tag-latest-release:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Reassign 'latest' tag
        run: |
          git tag -f latest
          git push origin latest
