name: Curated Lists

on:
  push:
    paths:
      - "**/tools/ontology-builder/src/ontology-references/**.json"
      - "**/artifact-schemas/**.json"
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install requkirements
        run: |
          pip install -r tools/ontology-builder/requirements.txt
      - name: ontology-processing
        run: |
          python3 ./tools/ontology-builder/src/validate_curated_lists.py
